/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export type WhitelistStruct = {
  owner: PromiseOrValue<string>;
  name: PromiseOrValue<string>;
  addresses: PromiseOrValue<string>[];
};

export type WhitelistStructOutput = [string, string, string[]] & {
  owner: string;
  name: string;
  addresses: string[];
};

export interface WhitelistFacetInterface extends utils.Interface {
  functions: {
    "createWhitelist(string,address[])": FunctionFragment;
    "getWhitelist(uint32)": FunctionFragment;
    "getWhitelistsLength()": FunctionFragment;
    "isWhitelisted(uint32,address)": FunctionFragment;
    "removeAddressesFromWhitelist(uint32,address[])": FunctionFragment;
    "setDonutWhiteListId(uint32)": FunctionFragment;
    "transferOwnershipOfWhitelist(uint32,address)": FunctionFragment;
    "updateWhitelist(uint32,address[])": FunctionFragment;
    "whitelistExists(uint32)": FunctionFragment;
    "whitelistOwner(uint32)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createWhitelist"
      | "getWhitelist"
      | "getWhitelistsLength"
      | "isWhitelisted"
      | "removeAddressesFromWhitelist"
      | "setDonutWhiteListId"
      | "transferOwnershipOfWhitelist"
      | "updateWhitelist"
      | "whitelistExists"
      | "whitelistOwner"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createWhitelist",
    values: [PromiseOrValue<string>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelist",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAddressesFromWhitelist",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setDonutWhiteListId",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnershipOfWhitelist",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateWhitelist",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistExists",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistOwner",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAddressesFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDonutWhiteListId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnershipOfWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistOwner",
    data: BytesLike
  ): Result;

  events: {
    "WhitelistCreated(uint32)": EventFragment;
    "WhitelistOwnershipTransferred(uint32,address)": EventFragment;
    "WhitelistUpdated(uint32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WhitelistCreated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "WhitelistOwnershipTransferred"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WhitelistUpdated"): EventFragment;
}

export interface WhitelistCreatedEventObject {
  whitelistId: number;
}
export type WhitelistCreatedEvent = TypedEvent<
  [number],
  WhitelistCreatedEventObject
>;

export type WhitelistCreatedEventFilter =
  TypedEventFilter<WhitelistCreatedEvent>;

export interface WhitelistOwnershipTransferredEventObject {
  whitelistId: number;
  newOwner: string;
}
export type WhitelistOwnershipTransferredEvent = TypedEvent<
  [number, string],
  WhitelistOwnershipTransferredEventObject
>;

export type WhitelistOwnershipTransferredEventFilter =
  TypedEventFilter<WhitelistOwnershipTransferredEvent>;

export interface WhitelistUpdatedEventObject {
  whitelistId: number;
}
export type WhitelistUpdatedEvent = TypedEvent<
  [number],
  WhitelistUpdatedEventObject
>;

export type WhitelistUpdatedEventFilter =
  TypedEventFilter<WhitelistUpdatedEvent>;

export interface WhitelistFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: WhitelistFacetInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createWhitelist(
      _name: PromiseOrValue<string>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[WhitelistStructOutput]>;

    getWhitelistsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    isWhitelisted(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    removeAddressesFromWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDonutWhiteListId(
      _newId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnershipOfWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    whitelistExists(
      whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[boolean] & { exists: boolean }>;

    whitelistOwner(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  createWhitelist(
    _name: PromiseOrValue<string>,
    _whitelistAddresses: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getWhitelist(
    _whitelistId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<WhitelistStructOutput>;

  getWhitelistsLength(overrides?: CallOverrides): Promise<BigNumber>;

  isWhitelisted(
    _whitelistId: PromiseOrValue<BigNumberish>,
    _whitelistAddress: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeAddressesFromWhitelist(
    _whitelistId: PromiseOrValue<BigNumberish>,
    _whitelistAddresses: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDonutWhiteListId(
    _newId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnershipOfWhitelist(
    _whitelistId: PromiseOrValue<BigNumberish>,
    _whitelistOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateWhitelist(
    _whitelistId: PromiseOrValue<BigNumberish>,
    _whitelistAddresses: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  whitelistExists(
    whitelistId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  whitelistOwner(
    _whitelistId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    createWhitelist(
      _name: PromiseOrValue<string>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<WhitelistStructOutput>;

    getWhitelistsLength(overrides?: CallOverrides): Promise<BigNumber>;

    isWhitelisted(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAddressesFromWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setDonutWhiteListId(
      _newId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnershipOfWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    whitelistExists(
      whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    whitelistOwner(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "WhitelistCreated(uint32)"(
      whitelistId?: PromiseOrValue<BigNumberish> | null
    ): WhitelistCreatedEventFilter;
    WhitelistCreated(
      whitelistId?: PromiseOrValue<BigNumberish> | null
    ): WhitelistCreatedEventFilter;

    "WhitelistOwnershipTransferred(uint32,address)"(
      whitelistId?: PromiseOrValue<BigNumberish> | null,
      newOwner?: PromiseOrValue<string> | null
    ): WhitelistOwnershipTransferredEventFilter;
    WhitelistOwnershipTransferred(
      whitelistId?: PromiseOrValue<BigNumberish> | null,
      newOwner?: PromiseOrValue<string> | null
    ): WhitelistOwnershipTransferredEventFilter;

    "WhitelistUpdated(uint32)"(
      whitelistId?: PromiseOrValue<BigNumberish> | null
    ): WhitelistUpdatedEventFilter;
    WhitelistUpdated(
      whitelistId?: PromiseOrValue<BigNumberish> | null
    ): WhitelistUpdatedEventFilter;
  };

  estimateGas: {
    createWhitelist(
      _name: PromiseOrValue<string>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWhitelistsLength(overrides?: CallOverrides): Promise<BigNumber>;

    isWhitelisted(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeAddressesFromWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDonutWhiteListId(
      _newId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnershipOfWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    whitelistExists(
      whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    whitelistOwner(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createWhitelist(
      _name: PromiseOrValue<string>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWhitelistsLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isWhitelisted(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeAddressesFromWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDonutWhiteListId(
      _newId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnershipOfWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateWhitelist(
      _whitelistId: PromiseOrValue<BigNumberish>,
      _whitelistAddresses: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    whitelistExists(
      whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    whitelistOwner(
      _whitelistId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
