/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Diamond__factory } from "./Diamond__factory";
export { ProofOfLessDiamond__factory } from "./ProofOfLessDiamond__factory";
