/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC721S,
  IERC721SInterface,
} from "../../../contracts/interface/IERC721S";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "metadataURI",
        type: "string",
      },
    ],
    name: "safeMint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC721S__factory {
  static readonly abi = _abi;
  static createInterface(): IERC721SInterface {
    return new utils.Interface(_abi) as IERC721SInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC721S {
    return new Contract(address, _abi, signerOrProvider) as IERC721S;
  }
}
