/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as campaignFactorySol from "./CampaignFactory.sol";
export type { campaignFactorySol };
import type * as interface from "./interface";
export type { interface };
export type { AccessCard } from "./AccessCard";
export type { IbToken } from "./IbToken";
export type { TUsdc } from "./TUsdc";
