/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  LibDonuts,
  LibDonutsInterface,
} from "../../../proofOfLess/libraries/LibDonuts";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "DonutInteract",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212204e5aa0aed328da077fe37137390980fc217fd8cf74ad4a958c8f1701b5adbfe664736f6c634300080b0033";

type LibDonutsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: LibDonutsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class LibDonuts__factory extends ContractFactory {
  constructor(...args: LibDonutsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<LibDonuts> {
    return super.deploy(overrides || {}) as Promise<LibDonuts>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): LibDonuts {
    return super.attach(address) as LibDonuts;
  }
  override connect(signer: Signer): LibDonuts__factory {
    return super.connect(signer) as LibDonuts__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LibDonutsInterface {
    return new utils.Interface(_abi) as LibDonutsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibDonuts {
    return new Contract(address, _abi, signerOrProvider) as LibDonuts;
  }
}
