/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DonutFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DonutFacet__factory>;
    getContractFactory(
      name: "ItemsFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItemsFacet__factory>;
    getContractFactory(
      name: "ItemsTransferFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ItemsTransferFacet__factory>;
    getContractFactory(
      name: "ProtocolFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProtocolFacet__factory>;
    getContractFactory(
      name: "QuestFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.QuestFacet__factory>;
    getContractFactory(
      name: "QuestFactoryFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.QuestFactoryFacet__factory>;
    getContractFactory(
      name: "TokenFactoryFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TokenFactoryFacet__factory>;
    getContractFactory(
      name: "VaultFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VaultFacet__factory>;
    getContractFactory(
      name: "WhitelistFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WhitelistFacet__factory>;
    getContractFactory(
      name: "InitDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitDiamond__factory>;
    getContractFactory(
      name: "LibDonuts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibDonuts__factory>;
    getContractFactory(
      name: "DiamondCutFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondCutFacet__factory>;
    getContractFactory(
      name: "DiamondLoupeFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondLoupeFacet__factory>;
    getContractFactory(
      name: "OwnershipFacet",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnershipFacet__factory>;
    getContractFactory(
      name: "IDiamondCut",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondCut__factory>;
    getContractFactory(
      name: "IDiamondLoupe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDiamondLoupe__factory>;
    getContractFactory(
      name: "IERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155__factory>;
    getContractFactory(
      name: "IERC1155TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155TokenReceiver__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "IERC173",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC173__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721TokenReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721TokenReceiver__factory>;
    getContractFactory(
      name: "LibDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibDiamond__factory>;
    getContractFactory(
      name: "LibERC1155",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC1155__factory>;
    getContractFactory(
      name: "LibERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LibERC721__factory>;
    getContractFactory(
      name: "ProofOfLessDiamond",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ProofOfLessDiamond__factory>;
    getContractFactory(
      name: "DiamondInit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DiamondInit__factory>;

    getContractAt(
      name: "DonutFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DonutFacet>;
    getContractAt(
      name: "ItemsFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItemsFacet>;
    getContractAt(
      name: "ItemsTransferFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ItemsTransferFacet>;
    getContractAt(
      name: "ProtocolFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ProtocolFacet>;
    getContractAt(
      name: "QuestFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.QuestFacet>;
    getContractAt(
      name: "QuestFactoryFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.QuestFactoryFacet>;
    getContractAt(
      name: "TokenFactoryFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.TokenFactoryFacet>;
    getContractAt(
      name: "VaultFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.VaultFacet>;
    getContractAt(
      name: "WhitelistFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.WhitelistFacet>;
    getContractAt(
      name: "InitDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.InitDiamond>;
    getContractAt(
      name: "LibDonuts",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibDonuts>;
    getContractAt(
      name: "DiamondCutFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondCutFacet>;
    getContractAt(
      name: "DiamondLoupeFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondLoupeFacet>;
    getContractAt(
      name: "OwnershipFacet",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnershipFacet>;
    getContractAt(
      name: "IDiamondCut",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondCut>;
    getContractAt(
      name: "IDiamondLoupe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IDiamondLoupe>;
    getContractAt(
      name: "IERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155>;
    getContractAt(
      name: "IERC1155TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155TokenReceiver>;
    getContractAt(
      name: "IERC165",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "IERC173",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC173>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "IERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721TokenReceiver",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721TokenReceiver>;
    getContractAt(
      name: "LibDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibDiamond>;
    getContractAt(
      name: "LibERC1155",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC1155>;
    getContractAt(
      name: "LibERC721",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LibERC721>;
    getContractAt(
      name: "ProofOfLessDiamond",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ProofOfLessDiamond>;
    getContractAt(
      name: "DiamondInit",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.DiamondInit>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
